# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6f7667438af61248a8ae1b3ab0cf7ab8941ac6e454e6cc785c6f9d154d65366eda24d6176354c87f8c2e7f7060cf60364c5ad2e3f856c50b50d44f9b74262c5

test:
  secret_key_base: a19b01569c7fd1357a5cc12e75d9297e0c6fa09da3594f3de5b88939aa6e19efe9dd6a3788ebc84531d4bbdb42ee11b1ca2e24609e363ce09531783702f1fc13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
